# Generated by Django 5.2.1 on 2025-06-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media_accounts',
            field=models.JSONField(blank=True, default=list, help_text='List of social media accounts: [{"platform": "twitter", "username": "johndoe", "url": "https://twitter.com/johndoe"}]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
